USE curso_banco;

CREATE TABLE estado (
	-- CONSTRAIT INLINE
	id INT NOT NULL AUTO_INCREMENT
    ,nome VARCHAR(200) NOT NULL UNIQUE
    ,sigla CHAR(2) NOT NULL UNIQUE
    ,ativo CHAR(1) NOT NULL DEFAULT 'S'
    ,data_cadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    -- CONSTRATINT OUT LINE
    ,CONSTRAINT coluna_de_regra_do_ativo CHECK (ativo IN ('S', 'N')) -- CRIAÇÃO DE REGRAS PARA A NOSSA TABELA
    ,CONSTRAINT pk_estado PRIMARY KEY (id) -- INDICANDO QUE NOSSA COLUNA id SERÁ A NOSSA CHAVE PRIMARIA
);

CREATE TABLE categoria(
	id INT NOT NULL AUTO_INCREMENT
	,nome VARCHAR(200) NOT NULL UNIQUE
    ,descricao VARCHAR(200) DEFAULT "SEM DESCRICAO"
    ,ativo CHAR(1) NOT NULL DEFAULT 'A'
    ,data_cadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,CONSTRAINT pk_categoria PRIMARY KEY (id)
);

CREATE TABLE tipo(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	,nome VARCHAR(200) NOT NULL UNIQUE
    ,descricao VARCHAR(255) DEFAULT "SEM DESCRICAO"
    ,ativo CHAR(1) NOT NULL DEFAULT 'A'
    ,data_cadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- INSERINDO VALORES EM ESTADO
INSERT INTO estado (nome, sigla) VALUES ("PARANA", "PR");
INSERT INTO estado (nome, sigla) VALUES ("SAO PAULO", "SP");
INSERT INTO estado (nome, sigla) VALUES ("RIO GRANDE DO SUL", "RS");
